import type { ResearchProject, ResearchTheme } from "../en/research";

export const researchProjects: ResearchProject[] = [
  {
    id: "mass-ai-verification-2026",
    title:
      "I+D Nacional «Proyecto de Desarrollo Tecnológico de Buques Totalmente Autónomos con IA» - Desarrollo de Tecnología de Verificación, Certificación y Demostración para Buques Totalmente Autónomos con IA",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2026.08 - 2032.12",
    status: "Ongoing",
    theme: "MASS & AI",
    secondaryThemes: ["Safety Systems"],
    flagship: true,
    isRnd: true,
  },
  {
    id: "safety-culture-program",
    title:
      "Investigación sobre la Construcción de un Sistema de Cultura de Educación en Seguridad para Navieras y Centros de Trabajo",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2026",
    status: "Ongoing",
    theme: "Safety Systems",
    flagship: true,
  },
  {
    id: "firefighting-mass",
    title:
      "Desarrollo de un Sistema de Extinción de Incendios Marítimos de Control Remoto Basado en Tecnología de Buques Autónomos",
    funder: "KIET",
    role: "Principal Researcher",
    period: "2023 - 2026",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
    isRnd: true,
  },
  {
    id: "mass-phase2",
    title: "Investigación en Desarrollo Tecnológico MASS, Fase 2 (Sector Naviero 7)",
    funder: "KIMST-KMI",
    role: "Principal Researcher",
    period: "2022 - 2025",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
    isRnd: true,
  },
  {
    id: "vts-cloud-platform",
    title: "Desarrollo de una Plataforma Integrada de VTS de Próxima Generación Basada en la Nube",
    funder: "KIMST",
    role: "Co-Researcher",
    period: "2021 - 2023",
    status: "Completed",
    theme: "VTS",
    flagship: true,
    isRnd: true,
  },
  {
    id: "vts-english-assessment",
    title: "Evaluación de la Competencia en Inglés de Comunicación de Operadores de VTS",
    funder: "Guardia Costera de Corea",
    role: "Principal Researcher",
    period: "2020",
    status: "Completed",
    theme: "VTS",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "bigdata-safety-forecast",
    title:
      "Desarrollo de Big Data de Información de Tráfico Marítimo y Tecnología de Sistema de Pronóstico de Seguridad",
    funder: "KRISO",
    role: "Advisor",
    period: "2019",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["VTS"],
    isRnd: true,
  },
  {
    id: "enav-policy-platform",
    title:
      "Investigación sobre la Construcción y Respuesta de la Plataforma de Políticas de e-Navigation",
    funder: "Ministerio de Océanos y Pesca",
    role: "Principal Researcher",
    period: "2019",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "public-vessel-management",
    title:
      "Análisis de Viabilidad de Apoyo a la Gestión y Operación de Buques Públicos y Desarrollo de Políticas Relacionadas",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2019",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "seafarer-legal-framework",
    title: "Estudio sobre la Reforma del Marco Legal para la Gente de Mar",
    funder: "Ministerio de Océanos y Pesca",
    role: "Advisor",
    period: "2018",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "mass-ai-navigation",
    title:
      "Desarrollo de Tecnología Fuente para un Sistema de Inteligencia Artificial de Control de Navegación para Buques Autónomos",
    funder: "KEIT",
    role: "Principal Researcher",
    period: "2017 - 2019",
    status: "Completed",
    theme: "MASS & AI",
    secondaryThemes: ["VTS"],
    flagship: true,
    isRnd: true,
  },
  {
    id: "safety-index",
    title: "Estudio de Viabilidad para un Índice de Seguridad Marítima Proactivo y Cuantitativo",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2017",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["Policy"],
  },
  {
    id: "seafarer-welfare-survey",
    title: "Encuesta Nacional sobre la Operación de Instalaciones de Bienestar para la Gente de Mar",
    funder: "Centro Coreano de Bienestar y Empleo de la Gente de Mar",
    role: "Co-Researcher",
    period: "2016",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-safety-management",
    title:
      "Desarrollo de Tecnología para un Sistema de Gestión Integral de Seguridad Marítima de Próxima Generación de la OMI",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2016 - 2020",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "accident-prevention",
    title: "Investigación Fundacional sobre un Sistema de Prevención de Accidentes Marítimos",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2015 - 2019",
    status: "Completed",
    theme: "Safety Systems",
  },
  {
    id: "jeju-maritime-school-feasibility",
    title:
      "Estudio de Viabilidad para el Establecimiento de una Escuela Secundaria Marítima Nacional para el Desarrollo de Recursos Humanos Marítimos",
    funder: "Oficina de Educación de la Provincia Autónoma Especial de Jeju",
    role: "Principal Researcher",
    period: "2015",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-job-analysis",
    title: "Análisis del Puesto de Trabajo de los Operadores de VTS y Estudio de Gestión de Factores Humanos",
    funder: "Ministerio de Seguridad Pública",
    role: "Principal Researcher",
    period: "2015",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "busan-vts-improvement",
    title:
      "Estudio Básico y Servicio de Diseño para la Mejora del Sistema VTS de la Región de Busan",
    funder: "Ministerio de Seguridad Pública",
    role: "Co-Researcher",
    period: "2014",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "vts-distress-simulator",
    title:
      "Desarrollo de Sistemas Complementarios para VTS y Simuladores de Entrenamiento de Respuesta a Emergencias",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2013",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "imo-strategic-agenda-2012",
    title: "Investigación sobre la Agenda Estratégica de la OMI",
    funder: "Ministerio de Océanos y Pesca",
    role: "Principal Researcher",
    period: "2012 - 2013",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-white-paper",
    title: "Libro Blanco de VTS: Veinte Años de Servicios de Tráfico Marítimo en Corea",
    funder: "Ministerio de Océanos y Pesca",
    role: "Principal Researcher",
    period: "2012",
    status: "Completed",
    theme: "VTS",
    flagship: true,
  },
  {
    id: "maritime-communication-smart-service",
    title:
      "Investigación para Asegurar la Mejora de las Comunicaciones de Buques y la Tecnología de Servicios Marítimos Inteligentes",
    funder: "KIMST",
    role: "Co-Researcher",
    period: "2012",
    status: "Completed",
    theme: "VTS",
    isRnd: true,
  },
  {
    id: "piracy-industry-resilience",
    title:
      "Investigación sobre el Fortalecimiento de la Capacidad de la Industria Naviera y la Cooperación Internacional para Prevenir Daños por Piratería",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2012",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "somalia-piracy-imo-response",
    title:
      "Investigación sobre el Fortalecimiento del Rol de la OMI y la Coordinación Internacional en Respuesta a la Piratería Somalí",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2011",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "imo-strategic-agenda-2010",
    title: "Investigación sobre la Agenda Estratégica de la OMI",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2010 - 2011",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "ship-management-globalization",
    title: "Investigación sobre el Avance y la Globalización de la Industria de Gestión de Buques",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2010",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-qualification-system",
    title: "Estudio sobre la Introducción de un Sistema de Cualificación y Evaluación para Operadores de VTS",
    funder: "Ministerio de Océanos y Pesca",
    role: "Principal Researcher",
    period: "2010",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "developing-countries-safety-cooperation",
    title:
      "Investigación de Proyecto de Cooperación para la Construcción de Sistemas de Seguridad Marítima en Países en Desarrollo",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2009 - 2011",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["Policy"],
  },
  {
    id: "global-safety-training-program",
    title:
      "Investigación de Planificación de un Programa Global de Educación en Seguridad Marítima e Infraestructura de Capacitación",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2009",
    status: "Completed",
    theme: "Safety Systems",
  },
  {
    id: "safety-technical-cooperation",
    title: "Investigación sobre la Activación de la Cooperación Técnica en Seguridad Marítima",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2008",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-agenda-analysis",
    title: "Servicio de Investigación sobre el Análisis y Desarrollo de la Agenda de Reuniones de la OMI",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2006",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-leading-group-program",
    title: "Servicio de Investigación para el Avance de Corea en el Programa de Grupo Líder de la OMI",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2005",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-mas-audit-response",
    title:
      "Servicio de Investigación sobre la Respuesta a la Introducción del Esquema de Auditoría de Estados Miembros de la OMI (MAS)",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2005",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "ptms-network-design",
    title: "Plan de Instalación y Servicio de Diseño de la Red Nacional PTMS",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2004",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "ecdis-auto-tracking-system",
    title:
      "Desarrollo de un Dispositivo de Seguimiento Automático de Buques Mediante Cartas Náuticas Electrónicas",
    funder: "Ministerio de Océanos y Pesca",
    role: "Co-Researcher",
    period: "2002",
    status: "Completed",
    theme: "VTS",
  },
];

export const researchThemes: ResearchTheme[] = [
  {
    key: "MASS & AI",
    name: "Buques Autónomos y MASS",
    description:
      "Control de navegación por IA, evaluación de la capacidad de evitar colisiones e investigación del elemento humano en buques de superficie autónomos.",
  },
  {
    key: "VTS",
    name: "VTS e IA Marítima",
    description:
      "Competencia de los operadores, evaluación de inglés basada en IA, y plataformas de gestión de tráfico de próxima generación.",
  },
  {
    key: "Safety Systems",
    name: "Sistemas de Seguridad Marítima",
    description:
      "Marcos de prevención de accidentes e índices de seguridad cuantitativos construidos a partir de datos nacionales de accidentes y tráfico.",
  },
  {
    key: "Policy",
    name: "OMI y Política Marítima",
    description:
      "Preparación regulatoria y coordinación internacional para las tecnologías marítimas emergentes.",
  },
];
