import type { ResearchProject, ResearchTheme } from "../en/research";

export const researchProjects: ResearchProject[] = [
  {
    id: "mass-ai-verification-2026",
    title:
      "AI 완전자율운항선박 기술개발 사업 - AI 완전자율운항선박 검인증 및 실증기술개발",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2026.08 - 2032.12",
    status: "Ongoing",
    theme: "MASS & AI",
    secondaryThemes: ["Safety Systems"],
    flagship: true,
    isRnd: true,
  },
  {
    id: "safety-culture-program",
    title: "선사와 사업장 안전 교육문화 활성화 체계마련 연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2026",
    status: "Ongoing",
    theme: "Safety Systems",
    flagship: true,
  },
  {
    id: "firefighting-mass",
    title: "자율운항 선박 기술을 적용한 원격제어가 가능한 해상 소방 시스템 개발",
    funder: "KIET",
    role: "Principal Researcher",
    period: "2023 - 2026",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
    isRnd: true,
  },
  {
    id: "mass-phase2",
    title: "자율운항선박 기술개발연구 2단계 (해운 7세부)",
    funder: "KIMST-KMI",
    role: "Principal Researcher",
    period: "2022 - 2025",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
    isRnd: true,
  },
  {
    id: "vts-cloud-platform",
    title: "클라우드 기반 차세대 VTS 통합 플랫폼 개발",
    funder: "KIMST",
    role: "Co-Researcher",
    period: "2021 - 2023",
    status: "Completed",
    theme: "VTS",
    flagship: true,
    isRnd: true,
  },
  {
    id: "vts-english-assessment",
    title: "선박교통관제사 관제영어능력 평가 연구",
    funder: "해양경찰청",
    role: "Principal Researcher",
    period: "2020",
    status: "Completed",
    theme: "VTS",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "bigdata-safety-forecast",
    title: "해상교통정보 빅데이터 구축 및 안전예보 시스템 기술 개발",
    funder: "KRISO",
    role: "Advisor",
    period: "2019",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["VTS"],
    isRnd: true,
  },
  {
    id: "enav-policy-platform",
    title: "e-Navigation 정책플랫폼 구축 조사대응 연구",
    funder: "해양수산부",
    role: "Principal Researcher",
    period: "2019",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "public-vessel-management",
    title: "관공선 관리 운영 지원타당성 분석 및 관련제도 마련 정책연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2019",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "seafarer-legal-framework",
    title: "선원분야 법률체계 개편방안 연구",
    funder: "해양수산부",
    role: "Advisor",
    period: "2018",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "mass-ai-navigation",
    title: "자율운항선박을 위한 운항관제 인공지능 시스템원천기술개발",
    funder: "KEIT",
    role: "Principal Researcher",
    period: "2017 - 2019",
    status: "Completed",
    theme: "MASS & AI",
    secondaryThemes: ["VTS"],
    flagship: true,
    isRnd: true,
  },
  {
    id: "safety-index",
    title: "선제적, 정량적 해사안전지수개발 기획연구",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2017",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["Policy"],
  },
  {
    id: "seafarer-welfare-survey",
    title: "전국 선원복지시설 운영실태 조사",
    funder: "한국선원복지고용센터",
    role: "Co-Researcher",
    period: "2016",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-safety-management",
    title: "IMO 차세대 해양안전 종합관리 체계 기술개발 연구",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2016 - 2020",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "accident-prevention",
    title: "해양안전사고 예방시스템 기반연구",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2015 - 2019",
    status: "Completed",
    theme: "Safety Systems",
  },
  {
    id: "jeju-maritime-school-feasibility",
    title: "해사인력육성에 따른 국립해사고 설립검토 연구",
    funder: "제주도교육청",
    role: "Principal Researcher",
    period: "2015",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-job-analysis",
    title: "해상교통관제사 직무분석 및 인적요인 관리방안 연구",
    funder: "국민안전처",
    role: "Principal Researcher",
    period: "2015",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "busan-vts-improvement",
    title: "부산권해역 해상교통관제 체계개선 기본조사 설계용역",
    funder: "국민안전처",
    role: "Co-Researcher",
    period: "2014",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "vts-distress-simulator",
    title: "해상교통관제 및 조난훈련시뮬레이터 부가시스템 개발",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2013",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "imo-strategic-agenda-2012",
    title: "IMO 전략과제 연구",
    funder: "해양수산부",
    role: "Principal Researcher",
    period: "2012 - 2013",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-white-paper",
    title: "선박교통관제(VTS) 백서 발간 연구",
    funder: "해양수산부",
    role: "Principal Researcher",
    period: "2012",
    status: "Completed",
    theme: "VTS",
    flagship: true,
  },
  {
    id: "maritime-communication-smart-service",
    title: "선박통신개선처리 및 해상스마트서비스 기술 확보를 위한 연구",
    funder: "KIMST",
    role: "Co-Researcher",
    period: "2012",
    status: "Completed",
    theme: "VTS",
    isRnd: true,
  },
  {
    id: "piracy-industry-resilience",
    title: "해적피해예방을 위한 해운업계 역량강화 및 국제협력 제고방안 연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2012",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "somalia-piracy-imo-response",
    title: "소말리아 해적대응을 위한 IMO의 기능 및 국제공조 강화방안 연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2011",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "imo-strategic-agenda-2010",
    title: "IMO 전략과제 연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2010 - 2011",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "ship-management-globalization",
    title: "선박관리업 선진화 및 글로벌화 연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2010",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-qualification-system",
    title: "해상교통관제사 자격제도 및 평가제도 도입연구",
    funder: "해양수산부",
    role: "Principal Researcher",
    period: "2010",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "developing-countries-safety-cooperation",
    title: "개발도상국 해사안전시스템 구축 협력사업 연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2009 - 2011",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["Policy"],
  },
  {
    id: "global-safety-training-program",
    title: "글로벌 해양안전교육 프로그램 및 훈련기반 구축 기획연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2009",
    status: "Completed",
    theme: "Safety Systems",
  },
  {
    id: "safety-technical-cooperation",
    title: "해사안전 기술협력 활성화 방안 연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2008",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-agenda-analysis",
    title: "IMO 회의 의제분석/의제개발 연구용역",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2006",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-leading-group-program",
    title: "IMO선도그룹 도약 프로그램 추진을 위한 연구 용역",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2005",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-mas-audit-response",
    title: "국제해사기구(IMO) 회원국 감사제도(MAS) 도입 대응 연구용역",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2005",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "ptms-network-design",
    title: "PTMS 전국종합망 설치계획 및 설계용역",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2004",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "ecdis-auto-tracking-system",
    title: "전자해도 이용 선박자동추적장치 개발연구",
    funder: "해양수산부",
    role: "Co-Researcher",
    period: "2002",
    status: "Completed",
    theme: "VTS",
  },
];

export const researchThemes: ResearchTheme[] = [
  {
    key: "MASS & AI",
    name: "자율운항선박 · MASS",
    description:
      "자율운항선박의 AI 항법제어, 충돌회피 능력평가, Human Element 연구.",
  },
  {
    key: "VTS",
    name: "VTS · 해양 AI",
    description:
      "관제사 직무역량, AI 기반 영어능력평가, 차세대 해상교통관제 플랫폼 연구.",
  },
  {
    key: "Safety Systems",
    name: "해양안전시스템",
    description:
      "국가 사고·교통 데이터를 기반으로 한 사고예방체계와 정량적 안전지수 개발.",
  },
  {
    key: "Policy",
    name: "IMO · 해사정책",
    description: "신기술 도입에 대비한 규제 대응방안과 국제협력 연구.",
  },
];
