// UI copy (table headers, section titles, field labels) for the printable
// resume document itself (everything inside `.paper` in resume-form.html),
// in all 4 resume languages. This is distinct from src/i18n/ui.ts, which is
// the public site's UI dictionary — the resume is a separate standalone
// document with its own chrome.
//
// The outer tool chrome (toolbar title, print button, hint text, tab labels,
// the "show dob/phone/email" checkboxes, and the confirm() dialog) stays
// Korean-only on purpose: it's `display:none` in @media print (never appears
// in the printed/PDF document) and the person operating the tool is Korean.
// Only what ends up inside `.paper` needs to vary by the selected language.

export const ui = {
  ko: {
    tableHeaders: {
      periodOrgRole: ["기간", "기관", "역할"],
      research: ["연도", "제목", "발주처", "역할"],
      education: ["기간", "학교", "학위"],
      papers: ["연도", "제목", "게재처", "비고"],
      presentations: ["연도", "제목", "장소 · 주최"],
      awards: ["연도", "수상명"],
      awardsWithNote: ["연도", "수상명", "비고"],
    },
    section: {
      currentRoles: "현재 주요 직위",
      education: "학력",
      careerHighlights: "주요 경력",
      representativeResearch: "대표 연구실적",
      books: "저서",
      awards: "수상",
      career: "경력",
      committee: "위원회 · 자문 · 심사위원 활동 이력 (연대순)",
      research: "연구실적",
      patents: "특허",
      representativePapers: "대표 논문",
      papers: "논문",
      talks: "외부강연 · 초청발표",
    },
    identityLabels: { org: "소속", title: "직위", license: "자격증", degree: "학위", dob: "생년월일", phone: "전화번호", email: "이메일" },
    footer: { date: "작성일자", org: "제출기관" },
    certify: "위 기재 내용이 사실임을 증명합니다.",
    repPapersLead: (n) => `전체 ${n}건은 Full Version 탭 참고.`,
    badge: (n) => `${n}건`,
    badgeAll: (n) => `${n}건 전체`,
    phonePlaceholder: "010-0000-0000",
  },
  en: {
    tableHeaders: {
      periodOrgRole: ["Period", "Institution", "Role"],
      research: ["Year", "Title", "Funder", "Role"],
      education: ["Period", "Institution", "Degree"],
      papers: ["Year", "Title", "Venue", "Note"],
      presentations: ["Year", "Title", "Venue · Host"],
      awards: ["Year", "Award"],
      awardsWithNote: ["Year", "Award", "Note"],
    },
    section: {
      currentRoles: "Current Key Positions",
      education: "Education",
      careerHighlights: "Career Highlights",
      representativeResearch: "Representative Research Projects",
      books: "Books",
      awards: "Awards",
      career: "Career",
      committee: "Committee, Advisory & Judging Activities (Chronological)",
      research: "Research Projects",
      patents: "Patents",
      representativePapers: "Representative Papers",
      papers: "Papers",
      talks: "External Lectures & Invited Talks",
    },
    identityLabels: { org: "Organization", title: "Position", license: "License", degree: "Degree", dob: "Date of Birth", phone: "Phone", email: "Email" },
    footer: { date: "Date", org: "Submitted To" },
    certify: "I certify that the above information is true and accurate.",
    repPapersLead: (n) => `See the Full Version tab for all ${n} papers.`,
    badge: (n) => `${n}`,
    badgeAll: (n) => `All ${n}`,
    phonePlaceholder: "+82-10-0000-0000",
  },
  ja: {
    tableHeaders: {
      periodOrgRole: ["期間", "機関", "役割"],
      research: ["年度", "タイトル", "発注機関", "役割"],
      education: ["期間", "学校", "学位"],
      papers: ["年度", "タイトル", "掲載誌", "備考"],
      presentations: ["年度", "タイトル", "場所・主催"],
      awards: ["年度", "受賞名"],
      awardsWithNote: ["年度", "受賞名", "備考"],
    },
    section: {
      currentRoles: "現在の主要職位",
      education: "学歴",
      careerHighlights: "主な経歴",
      representativeResearch: "代表研究実績",
      books: "著書",
      awards: "受賞",
      career: "経歴",
      committee: "委員会・諮問・審査委員活動歴（年代順）",
      research: "研究実績",
      patents: "特許",
      representativePapers: "代表論文",
      papers: "論文",
      talks: "外部講演・招待発表",
    },
    identityLabels: { org: "所属", title: "職位", license: "資格", degree: "学位", dob: "生年月日", phone: "電話番号", email: "メール" },
    footer: { date: "作成日", org: "提出先" },
    certify: "上記の記載内容が事実であることを証明します。",
    repPapersLead: (n) => `全${n}件は Full Version タブをご覧ください。`,
    badge: (n) => `${n}件`,
    badgeAll: (n) => `全${n}件`,
    phonePlaceholder: "+82-10-0000-0000",
  },
  es: {
    tableHeaders: {
      periodOrgRole: ["Periodo", "Institución", "Función"],
      research: ["Año", "Título", "Financiador", "Función"],
      education: ["Periodo", "Institución", "Titulación"],
      papers: ["Año", "Título", "Publicación", "Nota"],
      presentations: ["Año", "Título", "Lugar · Organizador"],
      awards: ["Año", "Premio"],
      awardsWithNote: ["Año", "Premio", "Nota"],
    },
    section: {
      currentRoles: "Cargos Actuales Principales",
      education: "Formación Académica",
      careerHighlights: "Trayectoria Profesional Destacada",
      representativeResearch: "Proyectos de Investigación Destacados",
      books: "Libros",
      awards: "Premios",
      career: "Experiencia Profesional",
      committee: "Historial de Actividades en Comités, Asesorías y Jurados (Cronológico)",
      research: "Proyectos de Investigación",
      patents: "Patentes",
      representativePapers: "Artículos Representativos",
      papers: "Artículos",
      talks: "Conferencias Externas y Ponencias Invitadas",
    },
    identityLabels: { org: "Organización", title: "Cargo", license: "Licencia", degree: "Titulación", dob: "Fecha de Nacimiento", phone: "Teléfono", email: "Correo Electrónico" },
    footer: { date: "Fecha", org: "Institución Receptora" },
    certify: "Certifico que la información anterior es verdadera y exacta.",
    repPapersLead: (n) => `Consulte la pestaña Full Version para ver los ${n} artículos completos.`,
    badge: (n) => `${n}`,
    badgeAll: (n) => `Total: ${n}`,
    phonePlaceholder: "+82-10-0000-0000",
  },
};

export const locales = ["ko", "en", "ja", "es"];
export const localeLabels = { ko: "한국어", en: "English", ja: "日本語", es: "Español" };
