import type { ResearchProject, ResearchTheme } from "../en/research";

export const researchProjects: ResearchProject[] = [
  {
    id: "mass-ai-verification-2026",
    title:
      "国家R&D「AI完全自律運航船技術開発事業」－AI完全自律運航船の検認証・実証技術開発",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2026.08 - 2032.12",
    status: "Ongoing",
    theme: "MASS & AI",
    secondaryThemes: ["Safety Systems"],
    flagship: true,
    isRnd: true,
  },
  {
    id: "safety-culture-program",
    title: "船社・事業所における安全教育文化の活性化体系構築に関する研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2026",
    status: "Ongoing",
    theme: "Safety Systems",
    flagship: true,
  },
  {
    id: "firefighting-mass",
    title: "自律運航船技術を応用した遠隔制御可能な海上消防システムの開発",
    funder: "KIET",
    role: "Principal Researcher",
    period: "2023 - 2026",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
    isRnd: true,
  },
  {
    id: "mass-phase2",
    title: "自律運航船技術開発研究 第2段階（海運セクター7）",
    funder: "KIMST-KMI",
    role: "Principal Researcher",
    period: "2022 - 2025",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
    isRnd: true,
  },
  {
    id: "vts-cloud-platform",
    title: "クラウド基盤 次世代VTS統合プラットフォームの開発",
    funder: "KIMST",
    role: "Co-Researcher",
    period: "2021 - 2023",
    status: "Completed",
    theme: "VTS",
    flagship: true,
    isRnd: true,
  },
  {
    id: "vts-english-assessment",
    title: "船舶交通管制士 管制英語能力評価に関する研究",
    funder: "海洋警察庁",
    role: "Principal Researcher",
    period: "2020",
    status: "Completed",
    theme: "VTS",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "bigdata-safety-forecast",
    title: "海上交通情報ビッグデータ構築および安全予報システム技術開発",
    funder: "KRISO",
    role: "Advisor",
    period: "2019",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["VTS"],
    isRnd: true,
  },
  {
    id: "enav-policy-platform",
    title: "e-Navigation政策プラットフォーム構築 調査対応研究",
    funder: "海洋水産部",
    role: "Principal Researcher",
    period: "2019",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "public-vessel-management",
    title: "官公船管理運営支援妥当性分析および関連制度整備政策研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2019",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "seafarer-legal-framework",
    title: "船員分野法体系改編方案研究",
    funder: "海洋水産部",
    role: "Advisor",
    period: "2018",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "mass-ai-navigation",
    title: "自律運航船のための運航管制人工知能システム基盤技術開発",
    funder: "KEIT",
    role: "Principal Researcher",
    period: "2017 - 2019",
    status: "Completed",
    theme: "MASS & AI",
    secondaryThemes: ["VTS"],
    flagship: true,
    isRnd: true,
  },
  {
    id: "safety-index",
    title: "先制的・定量的海事安全指数開発企画研究",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2017",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["Policy"],
  },
  {
    id: "seafarer-welfare-survey",
    title: "全国船員福祉施設運営実態調査",
    funder: "韓国船員福祉雇用センター",
    role: "Co-Researcher",
    period: "2016",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-safety-management",
    title: "IMO次世代海洋安全総合管理体系技術開発研究",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2016 - 2020",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "accident-prevention",
    title: "海洋安全事故予防システム基盤研究",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2015 - 2019",
    status: "Completed",
    theme: "Safety Systems",
  },
  {
    id: "jeju-maritime-school-feasibility",
    title: "海事人材育成のための国立海事高等学校設立検討研究",
    funder: "済州特別自治道教育庁",
    role: "Principal Researcher",
    period: "2015",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-job-analysis",
    title: "海上交通管制士職務分析および人的要因管理方案研究",
    funder: "国民安全処",
    role: "Principal Researcher",
    period: "2015",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "busan-vts-improvement",
    title: "釜山圏海域船舶交通管制体系改善基本調査設計業務",
    funder: "国民安全処",
    role: "Co-Researcher",
    period: "2014",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "vts-distress-simulator",
    title: "船舶交通管制および遭難訓練シミュレーター付加システム開発",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2013",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "imo-strategic-agenda-2012",
    title: "IMO戦略課題研究",
    funder: "海洋水産部",
    role: "Principal Researcher",
    period: "2012 - 2013",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-white-paper",
    title: "船舶交通管制（VTS）白書発刊研究",
    funder: "海洋水産部",
    role: "Principal Researcher",
    period: "2012",
    status: "Completed",
    theme: "VTS",
    flagship: true,
  },
  {
    id: "maritime-communication-smart-service",
    title: "船舶通信改善処理および海上スマートサービス技術確保のための研究",
    funder: "KIMST",
    role: "Co-Researcher",
    period: "2012",
    status: "Completed",
    theme: "VTS",
    isRnd: true,
  },
  {
    id: "piracy-industry-resilience",
    title: "海賊被害予防のための海運業界能力強化および国際協力向上方案研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2012",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "somalia-piracy-imo-response",
    title: "ソマリア海賊対応のためのIMOの機能および国際協調強化方案研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2011",
    status: "Completed",
    theme: "Policy",
    secondaryThemes: ["Safety Systems"],
  },
  {
    id: "imo-strategic-agenda-2010",
    title: "IMO戦略課題研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2010 - 2011",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "ship-management-globalization",
    title: "船舶管理業先進化およびグローバル化研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2010",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "vts-qualification-system",
    title: "海上交通管制士資格制度および評価制度導入研究",
    funder: "海洋水産部",
    role: "Principal Researcher",
    period: "2010",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "developing-countries-safety-cooperation",
    title: "開発途上国海事安全システム構築協力事業研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2009 - 2011",
    status: "Completed",
    theme: "Safety Systems",
    secondaryThemes: ["Policy"],
  },
  {
    id: "global-safety-training-program",
    title: "グローバル海洋安全教育プログラムおよび訓練基盤構築企画研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2009",
    status: "Completed",
    theme: "Safety Systems",
  },
  {
    id: "safety-technical-cooperation",
    title: "海事安全技術協力活性化方案研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2008",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-agenda-analysis",
    title: "IMO会議議題分析・議題開発研究業務",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2006",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-leading-group-program",
    title: "IMO先導グループ跳躍プログラム推進のための研究業務",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2005",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "imo-mas-audit-response",
    title: "国際海事機関（IMO）加盟国監査制度（MAS）導入対応研究業務",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2005",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "ptms-network-design",
    title: "PTMS全国総合網設置計画および設計業務",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2004",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "ecdis-auto-tracking-system",
    title: "電子海図を利用した船舶自動追跡装置開発研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2002",
    status: "Completed",
    theme: "VTS",
  },
];

export const researchThemes: ResearchTheme[] = [
  {
    key: "MASS & AI",
    name: "自律運航船・MASS",
    description: "自律運航船のAI航法制御、衝突回避能力評価、ヒューマンエレメント研究。",
  },
  {
    key: "VTS",
    name: "VTS・海洋AI",
    description: "管制士職務能力、AIベース英語能力評価、次世代船舶交通管制プラットフォーム研究。",
  },
  {
    key: "Safety Systems",
    name: "海上安全システム",
    description: "国家事故・交通データに基づく事故予防体系と定量的安全指数の開発。",
  },
  {
    key: "Policy",
    name: "IMO・海事政策",
    description: "新技術導入に備えた規制対応方策と国際協力に関する研究。",
  },
];
