import type { ResearchProject } from "../en/research";

export const researchProjects: ResearchProject[] = [
  {
    id: "mass-ai-verification-2026",
    title:
      "国家R&D「AI完全自律運航船技術開発事業」－AI完全自律運航船の検認証・実証技術開発",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2026.08 - 2032.12",
    status: "Ongoing",
    theme: "MASS & AI",
    flagship: true,
  },
  {
    id: "safety-culture-program",
    title: "船社・事業所における安全教育文化の活性化体系構築に関する研究",
    funder: "海洋水産部",
    role: "Co-Researcher",
    period: "2026",
    status: "Ongoing",
    theme: "Safety Systems",
    flagship: true,
  },
  {
    id: "firefighting-mass",
    title: "自律運航船技術を応用した遠隔制御可能な海上消防システムの開発",
    funder: "KIET",
    role: "Principal Researcher",
    period: "2023 - 2026",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
  },
  {
    id: "mass-phase2",
    title: "自律運航船技術開発研究 第2段階（海運セクター7）",
    funder: "KIMST-KMI",
    role: "Principal Researcher",
    period: "2022 - 2025",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
  },
  {
    id: "vts-cloud-platform",
    title: "クラウド基盤 次世代VTS統合プラットフォームの開発",
    funder: "KIMST",
    role: "Co-Researcher",
    period: "2021 - 2023",
    status: "Completed",
    theme: "VTS",
    flagship: true,
  },
  {
    id: "vts-english-assessment",
    title: "船舶交通管制士 管制英語能力評価に関する研究",
    funder: "海洋警察庁",
    role: "Principal Researcher",
    period: "2020",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "mass-ai-navigation",
    title: "自律運航船のための運航管制人工知能システム基盤技術開発",
    funder: "KEIT",
    role: "Principal Researcher",
    period: "2017 - 2019",
    status: "Completed",
    theme: "MASS & AI",
    flagship: true,
  },
  {
    id: "safety-index",
    title: "先制的・定量的海事安全指数開発企画研究",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2017",
    status: "Completed",
    theme: "Safety Systems",
  },
  {
    id: "imo-safety-management",
    title: "IMO次世代海洋安全総合管理体系技術開発研究",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2016 - 2020",
    status: "Completed",
    theme: "Policy",
  },
  {
    id: "accident-prevention",
    title: "海洋安全事故予防システム基盤研究",
    funder: "KIMST",
    role: "Principal Researcher",
    period: "2015 - 2019",
    status: "Completed",
    theme: "Safety Systems",
  },
  {
    id: "vts-job-analysis",
    title: "海上交通管制士職務分析および人的要因管理方案研究",
    funder: "国民安全処",
    role: "Principal Researcher",
    period: "2015",
    status: "Completed",
    theme: "VTS",
  },
  {
    id: "vts-white-paper",
    title: "船舶交通管制（VTS）白書発刊研究",
    funder: "海洋水産部",
    role: "Principal Researcher",
    period: "2012",
    status: "Completed",
    theme: "VTS",
    flagship: true,
  },
  {
    id: "vts-qualification-system",
    title: "海上交通管制士資格制度および評価制度導入研究",
    funder: "海洋水産部",
    role: "Principal Researcher",
    period: "2010",
    status: "Completed",
    theme: "VTS",
  },
];

export const researchThemes = [
  {
    name: "自律運航船・MASS",
    description: "自律運航船のAI航法制御、衝突回避能力評価、ヒューマンエレメント研究。",
  },
  {
    name: "VTS・海洋AI",
    description: "管制士職務能力、AIベース英語能力評価、次世代船舶交通管制プラットフォーム研究。",
  },
  {
    name: "海上安全システム",
    description: "国家事故・交通データに基づく事故予防体系と定量的安全指数の開発。",
  },
  {
    name: "IMO・海事政策",
    description: "新技術導入に備えた規制対応方策と国際協力に関する研究。",
  },
];
